# docker build -f Dockerfile.prod -t nest-server .
# docker run -p 8000:80 nest-server


# STAGE 1: Build
FROM node:17

WORKDIR /workspace

COPY package*.json ./

RUN yarn install

COPY . .

RUN npm run build


# STAGE 2: Run
CMD ["node", "dist/main"]
EXPOSE 3000