/* DO NOT EDIT THIS FILE */

#include <stdio.h>

#include "filter.h"
#include "pipeline.h"

int pipeline_serial(image_dir_t* image_dir) {
    pixel_t pixel = {.bytes = {0, 0, 0, 0}};
    while (1) {
        image_t* image = image_dir_load_next(image_dir);
        if (image == NULL) {
            break;
        }

        image_t* scaled_image = filter_scale_up(image, 2);
        image_destroy(image);
        if (scaled_image == NULL) {
            goto fail_exit;
        }

        image_t* hsv_image = filter_to_hsv(scaled_image);
        image_destroy(scaled_image);
        if (hsv_image == NULL) {
            goto fail_exit;
        }

        pixel.bytes[0] += 4;
        image_t* add_image = filter_add_pixel(hsv_image, &pixel);
        image_destroy(hsv_image);
        if (add_image == NULL) {
            goto fail_exit;
        }

        image_t* rgb_image = filter_to_rgb(add_image);
        image_destroy(add_image);
        if (rgb_image == NULL) {
            goto fail_exit;
        }

        image_dir_save(image_dir, rgb_image);
        printf(".");
        fflush(stdout);
        image_destroy(rgb_image);
    }

    printf("\n");
    return 0;

fail_exit:
    return -1;
}
