/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_PIPELINE_H_
#define INCLUDE_PIPELINE_H_

#include "image.h"

int pipeline_serial(image_dir_t* image_dir);
int pipeline_pthread(image_dir_t* image_dir);
int pipeline_tbb(image_dir_t* image_dir);

#endif /* INCLUDE_PIPELINE_H_ */
